using ImagePopularity.Core;
using System.Diagnostics;
using TorchSharp;
using static TorchSharp.torch;

namespace ImagePopularity.Trainer;

internal sealed class ModelTrainer
    : IDisposable
{
    private readonly TrainingOptions _options;
    private readonly Device _device;
    private readonly Random _random;
    private readonly ImageAugmentationOptions? _trainAugmentationOptions;
    private readonly PreprocessedImageCache _trainPreprocessedImageCache;
    private readonly PreprocessedImageCache _validationPreprocessedImageCache;
    private bool _disposed;

    public ModelTrainer(TrainingOptions options)
    {
        _options = options;

        if (_options.Epochs <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(options.Epochs), _options.Epochs, "epochs must be > 0.");
        }

        if (_options.BatchSize <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(options.BatchSize), _options.BatchSize, "batch-size must be > 0.");
        }

        if (_options.ValidationSplit is <= 0 or >= 1)
        {
            throw new ArgumentOutOfRangeException(nameof(options.ValidationSplit), _options.ValidationSplit, "validation-split must be in (0, 1).");
        }

        _device = TorchDeviceSelector.ResolveCuda();
        _random = new Random(options.Seed);
        _trainAugmentationOptions = options.EnableAugmentation
            ? new ImageAugmentationOptions
            {
                Enabled = true,
                HorizontalFlipProbability = (float)options.HorizontalFlipProbability,
                MaxRotationDegrees = (float)options.MaxRotationDegrees,
                BrightnessJitter = (float)options.BrightnessJitter,
                ContrastJitter = (float)options.ContrastJitter,
                SaturationJitter = (float)options.SaturationJitter,
                MinRandomCropScale = (float)options.MinRandomCropScale
            }
            : null;

        var cacheRoot = Path.GetFullPath(_options.PreprocessCacheDirectory);
        _trainPreprocessedImageCache = new PreprocessedImageCache(
            cacheDirectory: Path.Combine(cacheRoot, "train"),
            pipeline: new PreprocessedImageCache.PreprocessPipelineSpec
            {
                ImageSize = _options.TrainImageSize,
                Seed = _options.Seed,
                UseAugmentation = _options.EnableAugmentation,
                AugmentationOptions = _trainAugmentationOptions
            });
        _validationPreprocessedImageCache = new PreprocessedImageCache(
            cacheDirectory: Path.Combine(cacheRoot, "validation"),
            pipeline: new PreprocessedImageCache.PreprocessPipelineSpec
            {
                ImageSize = _options.TrainImageSize,
                Seed = _options.Seed,
                UseAugmentation = false,
                AugmentationOptions = null
            });
    }

    public void Run()
    {
        EnsureNotDisposed();
        var totalStopwatch = Stopwatch.StartNew();
        var modelOutputPath = _options.OutputModelPathAutoGenerated
            ? BuildTemporaryAutoOutputModelPath(_options.OutputModelPath)
            : _options.OutputModelPath;
        var bestModelSaved = false;

        var allSamples = LoadSamples();
        if (allSamples.Count < 100)
        {
            throw new InvalidOperationException("Not enough labeled images. Need at least 100 samples to train a reliable model.");
        }

        var (trainSamples, validationSamples) = SplitStratified(allSamples, _options.ValidationSplit);
        var pretrainedWeightsFile = PretrainedWeightsResolver.Resolve(_options);

        Console.WriteLine($"Preprocess cache directory: {Path.GetFullPath(_options.PreprocessCacheDirectory)}");
        Console.WriteLine("Preparing training preprocess cache (augment + pad resize + normalize)...");
        var trainPreprocessStopwatch = Stopwatch.StartNew();
        var trainCacheBuild = _trainPreprocessedImageCache.Build(
            trainSamples.Select(x => x.ImagePath),
            progressLabel: "Preprocess train");
        trainPreprocessStopwatch.Stop();
        Console.WriteLine(
            $"Training preprocess cache summary: total={trainCacheBuild.Total}, reused={trainCacheBuild.Reused}, created={trainCacheBuild.Created}, failed={trainCacheBuild.Failed}, elapsed={FormatElapsed(trainPreprocessStopwatch.Elapsed)}");
        Console.WriteLine("Preparing validation preprocess cache (pad resize + normalize)...");
        var validationPreprocessStopwatch = Stopwatch.StartNew();
        var validationCacheBuild = _validationPreprocessedImageCache.Build(
            validationSamples.Select(x => x.ImagePath),
            progressLabel: "Preprocess validation");
        validationPreprocessStopwatch.Stop();
        Console.WriteLine(
            $"Validation preprocess cache summary: total={validationCacheBuild.Total}, reused={validationCacheBuild.Reused}, created={validationCacheBuild.Created}, failed={validationCacheBuild.Failed}, elapsed={FormatElapsed(validationPreprocessStopwatch.Elapsed)}");

        Console.WriteLine($"Device: {_device.type}");
        Console.WriteLine($"Backbone: {_options.Backbone}");
        Console.WriteLine("Use pretrained backbone: true (forced)");
        Console.WriteLine($"Train image size: {_options.TrainImageSize}");
        Console.WriteLine($"Recommended inference image size: {_options.TrainImageSize} (auto = train-image-size)");
        Console.WriteLine($"Data augmentation enabled: {_options.EnableAugmentation}");
        Console.WriteLine($"Pretrained weights: {pretrainedWeightsFile}");
        Console.WriteLine($"Train samples: {trainSamples.Count}, Validation samples: {validationSamples.Count}");

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(modelOutputPath))!);

        using var model = new PopularityModel(
            new PopularityModelConfig { Backbone = _options.Backbone },
            backboneWeightsFile: pretrainedWeightsFile,
            device: CPU);
        model.to(_device);

        if (_options.FreezeBackboneEpochs > 0)
        {
            model.SetBackboneTrainable(false);
            Console.WriteLine($"Backbone frozen for first {_options.FreezeBackboneEpochs} epoch(s).");
        }
        else
        {
            model.SetBackboneTrainable(true);
        }

        var currentLearningRate = _options.LearningRate;
        var optimizer = CreateOptimizer(model, currentLearningRate);

        var bestValidationLoss = double.MaxValue;
        var epochTimings = new List<EpochTiming>(_options.Epochs);

        try
        {
            for (var epoch = 1; epoch <= _options.Epochs; epoch++)
            {
                var epochStopwatch = Stopwatch.StartNew();
                if (_options.FreezeBackboneEpochs > 0 &&
                    epoch == _options.FreezeBackboneEpochs + 1)
                {
                    model.SetBackboneTrainable(true);
                    optimizer.Dispose();
                    currentLearningRate = _options.FineTuneLearningRate;
                    optimizer = CreateOptimizer(model, currentLearningRate);
                    Console.WriteLine($"Backbone unfrozen at epoch {epoch}. Switched lr to {currentLearningRate:E5}.");
                }

                var trainMetrics = RunEpoch(model, trainSamples, optimizer, isTraining: true, epoch);
                var valMetrics = RunEpoch(model, validationSamples, optimizer: null, isTraining: false, epoch);
                epochStopwatch.Stop();

                epochTimings.Add(new EpochTiming(
                    epoch,
                    trainMetrics.Duration,
                    valMetrics.Duration,
                    epochStopwatch.Elapsed));

                Console.WriteLine(
                    $"Epoch {epoch}/{_options.Epochs} | " +
                    $"LR={currentLearningRate:E5} | " +
                    $"Train Loss={trainMetrics.Loss:F4}, Train Acc={trainMetrics.Accuracy:P2} | " +
                    $"Val Loss={valMetrics.Loss:F4}, Val Acc={valMetrics.Accuracy:P2} | " +
                    $"Train Time={FormatElapsed(trainMetrics.Duration)} | " +
                    $"Val Time={FormatElapsed(valMetrics.Duration)} | " +
                    $"Epoch Time={FormatElapsed(epochStopwatch.Elapsed)}");

                if (valMetrics.Loss < bestValidationLoss)
                {
                    bestValidationLoss = valMetrics.Loss;
                    model.save(modelOutputPath);
                    bestModelSaved = true;

                    var metadata = new PopularityModelMetadata
                    {
                        TrainingImageSize = _options.TrainImageSize,
                        RecommendedInferenceImageSize = _options.TrainImageSize,
                        Backbone = _options.Backbone,
                        UsedPretrainedBackbone = true,
                        PretrainedWeightsReference = Path.GetFileName(pretrainedWeightsFile),
                        Epochs = epoch,
                        TrainSamples = trainSamples.Count,
                        ValidationSamples = validationSamples.Count,
                        TrainedDevice = _device.type.ToString(),
                        TrainedAtUtc = DateTimeOffset.UtcNow
                    };

                    metadata.Save(modelOutputPath);

                    Console.WriteLine($"Saved best model: {modelOutputPath} (Val Loss={bestValidationLoss:F4})");
                }
            }

            if (bestModelSaved && _options.OutputModelPathAutoGenerated)
            {
                var finalOutputPath = _options.BuildCompletedAutoOutputModelPath(DateTimeOffset.Now, trainSamples.Count);
                PromoteAutoNamedOutput(modelOutputPath, finalOutputPath);
                modelOutputPath = finalOutputPath;
                Console.WriteLine($"Final auto-named model: {modelOutputPath}");
            }

            totalStopwatch.Stop();
            PrintTimingSummary(
                trainPreprocessStopwatch.Elapsed,
                validationPreprocessStopwatch.Elapsed,
                epochTimings,
                totalStopwatch.Elapsed);
        }
        finally
        {
            optimizer.Dispose();
        }
    }

    private EpochMetrics RunEpoch(
        PopularityModel model,
        IReadOnlyList<LabeledImageSample> samples,
        optim.Optimizer? optimizer,
        bool isTraining,
        int epoch)
    {
        var phaseStopwatch = Stopwatch.StartNew();

        if (isTraining)
        {
            model.train();

            // Keep the frozen backbone in eval mode even after model.train()
            // recursively switches child modules back to training mode.
            if (_options.FreezeBackboneEpochs > 0 && epoch <= _options.FreezeBackboneEpochs)
            {
                model.SetBackboneTrainable(false);
            }
        }
        else
        {
            model.eval();
        }

        double totalLoss = 0;
        long totalCorrect = 0;
        long totalCount = 0;

        using var noGrad = isTraining ? null : torch.no_grad();
        var plannedBatches = Math.Max(1, (int)Math.Ceiling(samples.Count / (double)_options.BatchSize));
        var phaseLabel = isTraining ? $"Train E{epoch}/{_options.Epochs}" : $"Valid E{epoch}/{_options.Epochs}";
        using var progress = new ConsoleProgressBar(phaseLabel, plannedBatches);

        var cache = isTraining ? _trainPreprocessedImageCache : _validationPreprocessedImageCache;
        var processedBatches = 0;
        foreach (var batch in CreateBatches(samples, _options.BatchSize, shuffle: isTraining, cache: cache))
        {
            try
            {
                using var inputs = batch.Inputs.to(_device);
                using var labels = batch.Labels.to(_device);

                if (isTraining)
                {
                    optimizer!.zero_grad();
                }

                using var logits = model.forward(inputs);
                using var loss = nn.functional.binary_cross_entropy_with_logits(logits, labels);

                if (isTraining)
                {
                    loss.backward();
                    optimizer!.step();
                }

                var batchSize = labels.shape[0];
                totalLoss += loss.item<float>() * (double)batchSize;

                using var probabilities = torch.sigmoid(logits);
                using var predictions = torch.ge(probabilities, 0.5);
                using var expected = torch.ge(labels, 0.5);
                using var correct = torch.eq(predictions, expected);

                totalCorrect += correct.sum().item<long>();
                totalCount += batchSize;
                processedBatches++;

                var avgLoss = totalCount == 0 ? 0 : totalLoss / totalCount;
                var avgAccuracy = totalCount == 0 ? 0 : totalCorrect / (double)totalCount;
                progress.Report(processedBatches, $"loss={avgLoss:F4} acc={avgAccuracy:P2}");
            }
            finally
            {
                batch.Inputs.Dispose();
                batch.Labels.Dispose();
            }
        }

        var metrics = new EpochMetrics
        {
            Loss = totalCount == 0 ? double.MaxValue : totalLoss / totalCount,
            Accuracy = totalCount == 0 ? 0 : totalCorrect / (double)totalCount,
            Duration = phaseStopwatch.Elapsed
        };
        progress.Complete($"loss={metrics.Loss:F4} acc={metrics.Accuracy:P2}");

        return metrics;
    }

    private IEnumerable<TrainingBatch> CreateBatches(
        IReadOnlyList<LabeledImageSample> samples,
        int batchSize,
        bool shuffle,
        PreprocessedImageCache cache)
    {
        var ordered = samples.ToList();
        if (shuffle)
        {
            ShuffleInPlace(ordered);
        }

        var imageTensorSize = 3 * _options.TrainImageSize * _options.TrainImageSize;

        for (var start = 0; start < ordered.Count; start += batchSize)
        {
            var count = Math.Min(batchSize, ordered.Count - start);
            var features = new float[count * imageTensorSize];
            var labels = new float[count];

            var valid = 0;

            for (var i = 0; i < count; i++)
            {
                var sample = ordered[start + i];

                try
                {
                    var chw = cache.LoadChw(sample.ImagePath);
                    Array.Copy(chw, 0, features, valid * imageTensorSize, imageTensorSize);
                    labels[valid] = sample.Label;
                    valid++;
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Skip broken image: {sample.ImagePath} ({ex.Message})");
                }
            }

            if (valid == 0)
            {
                continue;
            }

            if (valid < count)
            {
                Array.Resize(ref features, valid * imageTensorSize);
                Array.Resize(ref labels, valid);
            }

            var inputTensor = torch.tensor(features, dtype: ScalarType.Float32)
                .reshape(valid, 3, _options.TrainImageSize, _options.TrainImageSize);
            var labelTensor = torch.tensor(labels, dtype: ScalarType.Float32)
                .reshape(valid, 1);

            yield return new TrainingBatch(inputTensor, labelTensor);
        }
    }

    private IReadOnlyList<LabeledImageSample> LoadSamples()
    {
        var popular = EnumerateImages(_options.PopularDirectory)
            .Select(path => new LabeledImageSample(path, 1f))
            .ToList();

        var unpopular = EnumerateImages(_options.UnpopularDirectory)
            .Select(path => new LabeledImageSample(path, 0f))
            .ToList();

        if (_options.MaxSamplesPerClass > 0)
        {
            popular = popular
                .OrderBy(_ => _random.Next())
                .Take(_options.MaxSamplesPerClass)
                .ToList();

            unpopular = unpopular
                .OrderBy(_ => _random.Next())
                .Take(_options.MaxSamplesPerClass)
                .ToList();
        }

        if (popular.Count == 0 || unpopular.Count == 0)
        {
            throw new InvalidOperationException("Both popular and unpopular directories must contain images.");
        }

        Console.WriteLine($"Popular images: {popular.Count}");
        Console.WriteLine($"Unpopular images: {unpopular.Count}");

        return [.. popular, .. unpopular];
    }

    private IEnumerable<string> EnumerateImages(string directory)
    {
        if (!Directory.Exists(directory))
        {
            throw new DirectoryNotFoundException($"Directory not found: {directory}");
        }

        return Directory
            .EnumerateFiles(directory, "*", SearchOption.AllDirectories)
            .Where(SupportedImageFiles.IsSupported);
    }

    private (IReadOnlyList<LabeledImageSample> Train, IReadOnlyList<LabeledImageSample> Validation) SplitStratified(
        IReadOnlyList<LabeledImageSample> all,
        double validationSplit)
    {
        var popular = all.Where(x => x.Label > 0.5f).OrderBy(_ => _random.Next()).ToList();
        var unpopular = all.Where(x => x.Label < 0.5f).OrderBy(_ => _random.Next()).ToList();

        var popularValidationCount = Math.Max(1, (int)Math.Round(popular.Count * validationSplit));
        var unpopularValidationCount = Math.Max(1, (int)Math.Round(unpopular.Count * validationSplit));

        var validation = popular.Take(popularValidationCount)
            .Concat(unpopular.Take(unpopularValidationCount))
            .OrderBy(_ => _random.Next())
            .ToList();

        var train = popular.Skip(popularValidationCount)
            .Concat(unpopular.Skip(unpopularValidationCount))
            .OrderBy(_ => _random.Next())
            .ToList();

        return (train, validation);
    }

    private void ShuffleInPlace<T>(IList<T> values)
    {
        for (var i = values.Count - 1; i > 0; i--)
        {
            var j = _random.Next(i + 1);
            (values[i], values[j]) = (values[j], values[i]);
        }
    }

    private optim.Optimizer CreateOptimizer(PopularityModel model, double learningRate)
    {
        var trainableParameters = model.parameters()
            .Where(p => p.requires_grad)
            .ToArray();

        if (trainableParameters.Length == 0)
        {
            throw new InvalidOperationException("No trainable parameters found for optimizer.");
        }

        return optim.AdamW(trainableParameters, lr: learningRate, weight_decay: _options.WeightDecay);
    }

    private static void PrintTimingSummary(
        TimeSpan trainPreprocessDuration,
        TimeSpan validationPreprocessDuration,
        IReadOnlyList<EpochTiming> epochTimings,
        TimeSpan totalDuration)
    {
        Console.WriteLine("Timing summary:");
        Console.WriteLine($"  Preprocess train: {FormatElapsed(trainPreprocessDuration)}");
        Console.WriteLine($"  Preprocess validation: {FormatElapsed(validationPreprocessDuration)}");

        foreach (var epochTiming in epochTimings)
        {
            Console.WriteLine(
                $"  Epoch {epochTiming.Epoch}: train={FormatElapsed(epochTiming.TrainDuration)}, " +
                $"validation={FormatElapsed(epochTiming.ValidationDuration)}, total={FormatElapsed(epochTiming.TotalDuration)}");
        }

        var preprocessTotal = trainPreprocessDuration + validationPreprocessDuration;
        var epochTotal = TimeSpan.FromTicks(epochTimings.Sum(x => x.TotalDuration.Ticks));
        var otherDuration = totalDuration - preprocessTotal - epochTotal;
        if (otherDuration < TimeSpan.Zero)
        {
            otherDuration = TimeSpan.Zero;
        }

        Console.WriteLine($"  Other overhead: {FormatElapsed(otherDuration)}");
        Console.WriteLine($"  Total: {FormatElapsed(totalDuration)}");
    }

    private static string FormatElapsed(TimeSpan elapsed)
    {
        if (elapsed.TotalHours >= 1)
        {
            return elapsed.ToString(@"hh\:mm\:ss");
        }

        return elapsed.ToString(@"mm\:ss");
    }

    private static string BuildTemporaryAutoOutputModelPath(string baseOutputPath)
    {
        var directory = Path.GetDirectoryName(baseOutputPath);
        var extension = Path.GetExtension(baseOutputPath);
        var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(baseOutputPath);
        var temporaryFileName = string.IsNullOrEmpty(extension)
            ? $"{fileNameWithoutExtension}.autosave.tmp"
            : $"{fileNameWithoutExtension}.autosave{extension}";

        return string.IsNullOrWhiteSpace(directory)
            ? temporaryFileName
            : Path.Combine(directory, temporaryFileName);
    }

    private static void PromoteAutoNamedOutput(string sourceModelPath, string destinationModelPath)
    {
        var destinationDirectory = Path.GetDirectoryName(Path.GetFullPath(destinationModelPath));
        if (!string.IsNullOrWhiteSpace(destinationDirectory))
        {
            Directory.CreateDirectory(destinationDirectory);
        }

        File.Move(sourceModelPath, destinationModelPath, overwrite: true);

        var sourceMetadataPath = PopularityModelMetadata.GetMetadataPath(sourceModelPath);
        if (!File.Exists(sourceMetadataPath))
        {
            return;
        }

        var destinationMetadataPath = PopularityModelMetadata.GetMetadataPath(destinationModelPath);
        File.Move(sourceMetadataPath, destinationMetadataPath, overwrite: true);
    }

    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        _trainPreprocessedImageCache.Dispose();
        _validationPreprocessedImageCache.Dispose();
        _disposed = true;
    }

    private void EnsureNotDisposed()
    {
        if (_disposed)
        {
            throw new ObjectDisposedException(nameof(ModelTrainer));
        }
    }

    private readonly record struct LabeledImageSample(string ImagePath, float Label);

    private readonly record struct TrainingBatch(Tensor Inputs, Tensor Labels);

    private sealed class EpochMetrics
    {
        public double Loss { get; init; }

        public double Accuracy { get; init; }

        public TimeSpan Duration { get; init; }
    }

    private readonly record struct EpochTiming(int Epoch, TimeSpan TrainDuration, TimeSpan ValidationDuration, TimeSpan TotalDuration);
}
